# Generated by Django 3.2.19 on 2023-06-26 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230626_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='check_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.checkin'),
        ),
    ]
