# Generated by Django 3.2.19 on 2023-06-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_checkout_check_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='check_out_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='CheckOut',
        ),
    ]
