# Generated by Django 3.2.19 on 2023-06-19 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_desription_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='content',
        ),
    ]
