# Generated by Django 3.2.19 on 2023-06-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230626_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='check_in_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='check_out_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
