# Generated by Django 3.2.19 on 2023-06-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230626_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='check_in_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='%H:%M:%S'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_end',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
