# Generated by Django 3.2.19 on 2023-06-20 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_employeetype_event_eventtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeType',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(default='new employee', on_delete=django.db.models.deletion.CASCADE, to='core.eventtype'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='event_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
