# Generated by Django 3.2.19 on 2023-06-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230626_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='check_in_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
