# Generated by Django 3.2.19 on 2023-06-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230620_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='check_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
