# Generated by Django 3.2.19 on 2023-06-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20230621_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
